### ISSUE TITLE
keyword error when attempting plot_residuals_reference_sections

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#23]
**Describe the bug**
 When running dtscalibration.plot.plot_residuals_reference_sections(resid, sections=sections), python returns an 'unexpected keyword' error.

**To Reproduce**
1. Run plot_residuals_reference_sections
2. See error

**Additional context**
OS: Windows 7
Package version: just downloaded new version from github
xarray version: 0.10.9
matplotlib version: 2.1.2

```
Traceback (most recent call last):

  File "<ipython-input-28-e13673e52739>", line 1, in <module>
    calplot.plot_residuals_reference_sections(resid, sections=sections)

  File "D:\github\dtscal\dtscalibration\plot.py", line 67, in plot_residuals_reference_sections
    ax=main_ax, cbar_ax=cbar_ax, cbar_kwargs={'aspect': 20}, robust=robust)

  File "D:\Continuum\anaconda3\lib\site-packages\xarray\plot\plot.py", line 469, in __call__
    return plot(self._da, **kwargs)

  File "D:\Continuum\anaconda3\lib\site-packages\xarray\plot\plot.py", line 185, in plot
    return plotfunc(darray, **kwargs)

  File "D:\Continuum\anaconda3\lib\site-packages\xarray\plot\plot.py", line 771, in newplotfunc
    cbar = plt.colorbar(primitive, **cbar_kwargs)

  File "D:\Continuum\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2201, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)

  File "D:\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py", line 1864, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)

  File "D:\Continuum\anaconda3\lib\site-packages\matplotlib\colorbar.py", line 1368, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)

  File "D:\Continuum\anaconda3\lib\site-packages\matplotlib\colorbar.py", line 946, in __init__
    ColorbarBase.__init__(self, ax, **kw)

TypeError: __init__() got an unexpected keyword argument 'aspect'
```

**Comment by bdestombe** [comment]
Maybe we should add notebook examples of the plot functions. Those would tip us on these errors produced by Travis CI

**Comment by bdestombe** [comment]
Hi @BSchilperoort ,
I have added the plotting script to the Stokes variance example notebook. It passes all tests, so I think it has to do with a version compatibility.

Travis currently works with matplotlib version 3.0.2. Does upgrading to 3.0.2 solve the problem? Should we keep supporting Matplotlib 2? Support for backward compatibility requires extra work and is not the most fun part of the development process.

Cheers,
Bas

**Comment by bdestombe** [comment]
If it is still an issue, please reopen the issue
